Repository poetapp/frost-client, pull requests merged in 2018-05, with the labels that each got.

#14 bumps tslint-rules version
  package-lock.json
  package.json
Labels: in progress

#17 @po.et/tslint-rules@1.2.0
  package-lock.json
  package.json
  src/Frost.ts
  src/utils/utils.ts
Labels: quality

#18 Implements @po.et/poet-js
  package-lock.json
  package.json
  src/Frost.ts
Labels: feature, quality

#19 Update version @po.et/poet-js
  package-lock.json
  package.json
Labels: feature

#21 Tasks Greenkeeper
  .travis.yml
Labels: quality
